import cv2 as cv
print("Program version 1.0.1")
print("Creator = Okmeque1")
print("This program will display 3 images.")
a = input("Please enter a valid photo file.The format must be A:\Directory\Subdirectory\photo.format → ")
b = input("Please enter a valid photo file.The format must be A:\Directory\Subdirectory\photo.format → ")
c = input("Please enter a valid photo file.The format must be A:\Directory\Subdirectory\photo.format → ")
img1 = cv.imread(a)
cv.imshow('Image 1',img1)
cv.waitKey(10000)
img2 = cv.imread(b)
cv.imshow('Image 2',img2)
cv.waitKey(1000)
img3 = cv.imread(c)
cv.imshow('Image 3',img3)
cv.waitKey(1000000000)
